services:
  validator:
    image: "0g-chain:${TAG}"
    build:
      context: .
      args:
        TAG: "${TAG}"
    container_name: 0g-chain-validator
    env_file:
      - .env
    volumes:
      - "${CONFIG_DIR}:/root/.0gchain/config"
      - 0g_validator_data:/root/.0gchain/data
    ports:
      - "${RPC_PORT}:26656"
      - "${WS_PORT}:26657"
    restart: unless-stopped
    command:
      - 0gchaind
      - start

  node_exporter:
    image: prom/node-exporter:latest
    container_name: 0g-chain-validator-node-exporter
    restart: unless-stopped
    pid: host
    volumes:
      - /:/host:ro,rslave
    command:
      - --path.rootfs=/host

  prometheus:
    image: prom/prometheus:latest
    container_name: 0g-chain-validator-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - 0g_validator_prometheus_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: 0g-chain-validator-grafana
    restart: unless-stopped
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - 0g_validator_grafana_data:/var/lib/grafana
    ports:
      - "${GRAFANA_PORT}:3000"

volumes:
  0g_validator_config:
  0g_validator_data:
  0g_validator_prometheus_data:
  0g_validator_grafana_data:
