services:
  validator:
    image: 0g-chain:${TAG}
    build:
      context: .
      args:
        TAG: ${TAG}
    container_name: 0g-chain-validator
    env_file:
      - .env
    volumes:
      - ./0gchain:/root/.0gchain
    ports:
      - "26656-26657:26656-26657"
    restart: unless-stopped
    command:
      - 0gchaind
      - start

  node_exporter:
    image: prom/node-exporter:latest
    container_name: 0g-chain-validator-node-exporter
    restart: unless-stopped
    pid: host
    volumes:
      - /:/host:ro,rslave
    command:
      - --path.rootfs=/host

  prometheus:
    image: prom/prometheus:latest
    container_name: 0g-chain-validator-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: 0g-chain-validator-grafana
    restart: unless-stopped
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    ports:
      - "${GRAFANA_PORT}:3000"

volumes:
  prometheus_data:
  grafana_data:
